/*
redefine how we find the sizeof an incomplete class.
*/

/* declare the incomplete class. */
Incomplete(...) {
    _();
    ~();
    void greet();

    /*
    every class has a sizeof() function generated by the compiler.
    the user cannot overload it.
    */
    /*intptr sizeof();*/
}

/* define the incomplete class. */
Incomplete(
    ...,
    int x_
) {
    _() {
        __println("Incomplete:ctor");
    }

    ~() {
        __println("Incomplete:dtor");
    }

    void greet() {
        __println("Hello, World!");
    }

    /*
    the compiler creates this function automagically.
    if the class is local to this source file,
    then this function is a private.
    if the class is declared in a header .slh file,
    then this function is exported public in the .o.
    sizeof and pinit follow the same rules.
    they are called by the consumer at the same time.
    */
    /*intptr sizeof() = {
        return 4;
    }*/
}

int32 main() {
    Incomplete inc;
    inc.greet();

    /* builtin sizeof variable */
    size = sizeof(inc);
    __println("sizeof(inc)<4>=" + size);

    /* builtin sizeof type */
    size = sizeof(Incomplete);
    __println("sizeof(Incomplete)<4>=" + size);

    /* sizeof by class method */
    size = inc.sizeof();
    __println("inc.sizeof()<4>=" + size);

    /* sizeof by type */
    size = Incomplete.sizeof();
    __println("Incomplete.sizeof()<4>=" + size);

    return 0;
}
